name: 'Terragrunt CI'

on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: staging
  AWS_OIDC_ROLE_ARN: arn:aws:iam::214633882441:role/github-terraform-deployer

jobs:
  Terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Configure AWS credentials using OIDC
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    # Install the latest version of Terragrunt CLI and configure the Terragrunt CLI configuration file with a Terragrunt Cloud user API token
    - name: Install Terraform and Terragrunt
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin
        curl -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.28.0/terragrunt_linux_amd64
        sudo chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin

    # Initialize a new or existing Terragrunt working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terragrunt Init
      run: terragrunt init --terragrunt-non-interactive

    # Generates an execution plan for Terragrunt
    - name: Terragrunt Plan
      run: terragrunt run-all plan --terragrunt-non-interactive

    # On push to main, build or change infrastructure according to Terragrunt configuration files
    - name: Terragrunt Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terragrunt run-all apply --terragrunt-non-interactive
